import './styles.css';

const phone = '56975572276';
const message = 'Hola me gustaría saber más sobre soluciones fotovoltaicas para bajar mi cuenta de electricidad';
const whatsapp = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
const track = (event) => window.dataLayer?.push({ event });
const icon = (name) => `<svg aria-hidden="true" viewBox="0 0 24 24"><use href="#${name}"/></svg>`;
const brand = `<a class="brand" href="/" aria-label="Lautaro Solar, inicio"><span class="mark">LS</span><span>Lautaro<br/><i>Solar</i></span></a>`;
const nav = `<header><div class="shell nav">${brand}<button class="menu" aria-label="Abrir menú" aria-expanded="false">Menú</button><nav aria-label="Navegación principal"><a href="/#soluciones">Soluciones</a><a href="/#proceso">Proceso</a><a href="/#proyectos">Proyectos</a><a href="/#nosotros">Nosotros</a></nav><a class="button button-small" data-track="whatsapp_header" href="${whatsapp}" target="_blank" rel="noreferrer">WhatsApp</a></div></header>`;
const footer = `<footer><div class="shell footer-top">${brand}<div><b>Conversemos</b><a href="tel:+56975572276" data-track="phone_click">+56 9 7557 2276</a><a href="mailto:cotizalautarosolar@gmail.com">cotizalautarosolar@gmail.com</a></div><div><b>Horario de atención</b><p>Lunes a viernes · 09:00 a 18:00<br/>Sábado · 09:00 a 13:00</p><a class="map-link" href="https://maps.app.goo.gl/pAMPaBaKdKERweTB8" target="_blank" rel="noreferrer">Atención en Lautaro, solo con reserva</a></div><div><b>Encuéntranos</b><a href="https://www.instagram.com/lautarosolar_/" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.facebook.com/profile.php?id=61574960718002" target="_blank" rel="noreferrer">Facebook</a><p>Desde Los Ángeles hasta Puerto Montt, de mar a cordillera.</p></div></div><div class="shell footer-bottom"><span>© ${new Date().getFullYear()} Lautaro Solar</span><span><a href="/privacidad/">Privacidad</a><a href="/terminos/">Términos</a><a href="/cookies/">Cookies</a></span></div></footer>`;

const legal = (title, copy) => `${nav}<main class="legal shell"><span class="eyebrow">Información del sitio</span><h1>${title}</h1><p class="intro">${copy}</p><div class="legal-copy"><h2>Información pendiente de completar</h2><p>Esta página presenta una estructura informativa inicial. Los datos legales específicos de Lautaro Solar, incluyendo razón social, RUT y condiciones aplicables, se incorporarán cuando estén disponibles.</p><h2>Contacto</h2><p>Para consultas, escribe a <a href="mailto:cotizalautarosolar@gmail.com">cotizalautarosolar@gmail.com</a> o llama al <a href="tel:+56975572276">+56 9 7557 2276</a>.</p></div></main>${footer}`;

const landing = () => `${nav}<main>
<section class="hero"><div class="hero-photo" role="img" aria-label="Paneles solares instalados sobre una vivienda"></div><div class="shell hero-grid"><div class="hero-copy"><p class="eyebrow">Ingeniería fotovoltaica en el sur de Chile</p><h1>Genera tu propia energía.<br/><em>Olvídate de la cuenta de electricidad.</em></h1><p>Soluciones fotovoltaicas a tu medida para que tu casa, negocio o empresa funcione con mayor independencia energética. El ahorro depende del consumo y las características de cada proyecto.</p><div class="actions"><a href="#cotiza" class="button" data-track="hero_quote">Solicita una cotización</a><a href="${whatsapp}" target="_blank" rel="noreferrer" class="text-link" data-track="whatsapp_hero">Escríbenos por WhatsApp <span>↗</span></a></div></div><aside class="hero-note"><span>Proyecto completo</span><p>Desde la evaluación hasta la puesta en marcha.</p></aside></div></section>
<section class="trust shell" aria-label="Lautaro Solar en números"><div><strong>2</strong><span>años de experiencia</span></div><div><strong>9</strong><span>proyectos terminados</span></div><div><strong>5</strong><span>comunas con proyectos realizados</span></div><p>Traiguén · Perquenco · Lautaro · Temuco · Carahue</p></section>
<section id="soluciones" class="solutions shell"><div class="section-head"><span class="eyebrow">Soluciones</span><h2>La energía que necesitas,<br/>diseñada para tu realidad.</h2><p>Evaluamos cada proyecto para definir una solución que responda a su consumo, ubicación y objetivos.</p></div><div class="solution-list"><article class="solution primary"><span class="number">01</span><div><span class="eyebrow">Conectado a red</span><h3>On-Grid<br/>NetBilling</h3><p>Genera energía para tu consumo e inyecta los excedentes a la red.</p></div><div class="price"><small>Valor referencial</small><b>Desde $2.000.000</b><small>Depende de las características del proyecto.</small></div></article><article class="solution"><span class="number">02</span><div><span class="eyebrow">Autonomía</span><h3>Off-Grid</h3><p>Sistema independiente de la red, con paneles y baterías.</p></div><div class="price"><small>Valor referencial</small><b>Desde $3.000.000</b></div></article><article class="solution"><span class="number">03</span><div><span class="eyebrow">Respaldo y flexibilidad</span><h3>Híbrida</h3><p>Combina paneles, baterías y red eléctrica.</p></div><div class="price"><small>Valor referencial</small><b>Desde $5.000.000</b></div></article></div></section>
<section class="value"><div class="shell value-grid"><div class="value-image" role="img" aria-label="Detalle de paneles solares frente a paisaje del sur de Chile"></div><div><span class="eyebrow">Por qué Lautaro Solar</span><h2>Ingeniería y ejecución en un mismo equipo.</h2><p>Nos hacemos cargo del recorrido completo para entregar una solución bien pensada, segura y alineada con cada proyecto.</p><ul><li>Levantamiento y evaluación</li><li>Diseño y dimensionamiento</li><li>Suministro e instalación</li><li>Configuración y puesta en marcha</li><li>Documentación y tramitación correspondiente</li></ul><p class="fine">Utilizamos equipos y materiales autorizados por la SEC. El proceso está a cargo de un Instalador Autorizado SEC Clase A.</p></div></div></section>
<section id="proceso" class="process shell"><div class="section-head"><span class="eyebrow">Así trabajamos</span><h2>De la primera conversación<br/>a la energía en marcha.</h2></div><ol><li><b>01</b><h3>Contacto</h3><p>Cuéntanos sobre tu casa, negocio o empresa.</p></li><li><b>02</b><h3>Evaluación</h3><p>Revisamos las necesidades de tu proyecto.</p></li><li><b>03</b><h3>Diseño y propuesta</h3><p>Definimos una solución a tu medida.</p></li><li><b>04</b><h3>Instalación</h3><p>Ejecutamos el proyecto con atención al detalle.</p></li><li><b>05</b><h3>Puesta en marcha</h3><p>Configuramos y dejamos funcionando tu sistema.</p></li></ol></section>
<section id="proyectos" class="projects"><div class="shell"><div class="section-head row"><div><span class="eyebrow">Proyectos realizados</span><h2>Trabajo real,<br/>detalles por sumar.</h2></div><p>Esta galería está preparada para presentar próximos proyectos con sus fotografías, ubicación y especificaciones.</p></div><div class="project-grid"><article><div class="project-placeholder">Fotografía del proyecto</div><span>Proyecto · Ubicación · Tipo de instalación</span></article><article><div class="project-placeholder warm">Fotografía del proyecto</div><span>Proyecto · Ubicación · Tipo de instalación</span></article><article><div class="project-placeholder dark">Fotografía del proyecto</div><span>Proyecto · Ubicación · Tipo de instalación</span></article></div></div></section>
<section id="nosotros" class="about shell"><span class="eyebrow">Sobre Lautaro Solar</span><div><h2>Soluciones solares desde Lautaro, para el sur de Chile.</h2><p>Desde 2024, somos un equipo dedicado a crear soluciones de energía solar para viviendas, negocios e industrias. Combinamos experiencia técnica y atención cercana para diseñar proyectos adaptados al consumo, al lugar y a los objetivos de cada cliente.</p><a href="#cotiza" class="text-link">Hablemos de tu proyecto <span>↘</span></a></div></section>
<section class="faq shell"><div class="section-head"><span class="eyebrow">Preguntas frecuentes</span><h2>Lo esencial para<br/>dar el primer paso.</h2></div><div class="accordion"><details><summary>¿Qué zonas cubre Lautaro Solar?</summary><p>Trabajamos desde Los Ángeles hasta Puerto Montt, de mar a cordillera.</p></details><details><summary>¿Qué tipos de sistemas instalan?</summary><p>Ofrecemos soluciones On-Grid NetBilling, Off-Grid e Híbridas.</p></details><details><summary>¿Puedo solicitar una cotización?</summary><p>Sí. Completa el formulario o escríbenos por WhatsApp para contarnos sobre tu proyecto.</p></details><details><summary>¿Cuál es la diferencia entre los sistemas?</summary><p>On-Grid se conecta a la red; Off-Grid opera de forma independiente con baterías; el sistema Híbrido combina paneles, baterías y red eléctrica.</p></details></div></section>
<section id="cotiza" class="quote"><div class="shell quote-grid"><div><span class="eyebrow">Solicita tu cotización</span><h2>Tu proyecto comienza con una buena conversación.</h2><p>Déjanos tus datos y la información que tengas. Te contactaremos para conocer mejor tu necesidad.</p><a href="tel:+56975572276" data-track="phone_quote">+56 9 7557 2276</a></div><form id="quote-form" novalidate><div class="fields"><label>Nombre<input name="name" required autocomplete="name"/><small></small></label><label>Teléfono<input name="phone" required inputmode="tel" autocomplete="tel"/><small></small></label><label>Correo<input name="email" required type="email" autocomplete="email"/><small></small></label><label>Empresa<input name="company" autocomplete="organization"/></label><label>Ciudad o comuna<input name="city" required autocomplete="address-level2"/><small></small></label><label>Solución de interés<select name="solution" required><option value="">Selecciona una opción</option><option>On-Grid NetBilling</option><option>Off-Grid</option><option>Híbrida</option><option>Necesito orientación</option></select><small></small></label></div><label>Cuéntanos sobre tu consumo o proyecto<textarea name="message" required rows="4"></textarea><small></small></label><button class="button" type="submit">Enviar solicitud</button><p class="form-status" aria-live="polite"></p><p class="form-note">La integración de envío requiere configurar un servicio seguro en el servidor antes de publicar.</p></form></div></section>
<section class="last-cta"><div class="shell"><span class="eyebrow">Energía a tu medida</span><h2>Conversemos sobre<br/>tu próxima instalación.</h2><a class="button light" href="${whatsapp}" target="_blank" rel="noreferrer" data-track="whatsapp_final">Escríbenos por WhatsApp</a></div></section></main>${footer}<a class="whatsapp-float" href="${whatsapp}" target="_blank" rel="noreferrer" aria-label="Escríbenos por WhatsApp" data-track="whatsapp_float">WA</a>`;

const path = window.location.pathname;
let content = landing();
if (path.includes('gracias')) content = `${nav}<main class="thanks shell"><span class="eyebrow">Solicitud recibida</span><h1>Gracias por contactarnos.</h1><p>Recibimos tu solicitud. Si prefieres, también puedes escribirnos directamente por WhatsApp.</p><div class="actions"><a class="button" href="${whatsapp}" target="_blank" rel="noreferrer">Escríbenos por WhatsApp</a><a class="text-link" href="/">Volver al inicio</a></div></main>${footer}`;
if (path.includes('privacidad')) content = legal('Política de privacidad', 'Cómo tratamos la información que nos compartes.');
if (path.includes('terminos')) content = legal('Términos y condiciones', 'Información general sobre el uso de este sitio.');
if (path.includes('cookies')) content = legal('Política de cookies', 'Información sobre las tecnologías de navegación utilizadas en este sitio.');
if (path.includes('/404')) content = `${nav}<main class="thanks shell"><span class="eyebrow">Error 404</span><h1>Esta página no está disponible.</h1><p>Tal vez el enlace cambió o la página ya no existe.</p><a class="button" href="/">Volver al inicio</a></main>${footer}`;
document.querySelector('#app').innerHTML = `${content}<svg class="icons"><symbol id="sun" viewBox="0 0 24 24"/></svg>`;
document.querySelectorAll('[data-track]').forEach(el => el.addEventListener('click', () => track(el.dataset.track)));
const menu = document.querySelector('.menu');
menu?.addEventListener('click', () => { const open = document.body.classList.toggle('nav-open'); menu.setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('header nav a').forEach(a => a.addEventListener('click', () => document.body.classList.remove('nav-open')));
const form = document.querySelector('#quote-form');
form?.addEventListener('submit', async (e) => { e.preventDefault(); let okay = true; form.querySelectorAll('[required]').forEach(input => { const error = input.nextElementSibling; const invalid = !input.value.trim() || (input.type === 'email' && !input.validity.valid); input.setAttribute('aria-invalid', invalid); if (error) error.textContent = invalid ? 'Completa este campo correctamente.' : ''; if (invalid) okay = false; }); const status = form.querySelector('.form-status'); const submit = form.querySelector('button'); if (!okay) { status.textContent = 'Revisa los campos marcados.'; return; } const endpoint = import.meta.env.VITE_FORM_ENDPOINT; if (!endpoint) { status.textContent = 'El envío aún no está configurado. Escríbenos por WhatsApp para cotizar.'; return; } status.textContent = 'Enviando solicitud…'; submit.disabled = true; try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); if (!response.ok) throw new Error('request failed'); status.textContent = 'Solicitud enviada. Redirigiendo…'; track('form_submit'); window.setTimeout(() => window.location.assign('/gracias/'), 300); } catch { status.textContent = 'No pudimos enviar la solicitud. Intenta por WhatsApp o vuelve a intentarlo.'; submit.disabled = false; } });
